# NOTE: 이 파일은 어떤 코드도 읽지 않는다. 실제로 로드되는 것은
#   adaptor/config/{config.toml,robots.hcl,extensions.hcl} 뿐이고
#   (adaptor/config/config.py 가 __file__ 기준 절대경로로 연다),
#   로봇 배포도 adaptor/ 만 올라간다
#   (scripts/update-jibot-adapter-over-ssh.sh LOCAL_ADAPTER_DIR="adaptor").
#   여기 값을 고쳐도 실행에 반영되지 않는다 — 현장 기록용 사본으로만 볼 것.
#   반영하려면 adaptor/config/ 쪽 같은 이름 파일을 고칠 것.

# Generated by scripts/convert-robots-toml-to-hcl.py
# 주석은 변환되지 않는다. config/robots.hcl.example을 참고해 정리할 것.

robot "HN-SH6-TR-001" {
  vehicle_ip   = "10.8.8.8"
  vehicle_port = 7273
  ezi_io       = "10.8.8.87"
  ezi_motor    = "10.8.8.2"
}
