#!/usr/bin/env python3
"""config/robots.toml을 config/robots.hcl로 변환한다 (일회성 마이그레이션).

사용:
    python scripts/convert-robots-toml-to-hcl.py adaptor/config/robots.toml \
        -o adaptor/config/robots.hcl

[[robot]] 항목의 id는 블록 라벨이 되고 나머지 키는 그대로 옮긴다. 주석은
TOML 파서가 버리므로 보존되지 않는다. 변환 후 robots.hcl을 열어 주석을
직접 옮기고, config/robots.hcl.example을 참고해 정리할 것.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    import tomli as tomllib


def _reject_tables(value: object, rid: str, key: str) -> None:
    """Refuse nested tables instead of stringifying them.

    Without this a ``[robot.x]`` sub-table falls through to ``str(value)`` and
    lands in the output as a quoted Python repr — ``x = "{'foo': 1}"`` — which
    is valid HCL and therefore fails silently. Rendering it as a real HCL
    object would not help either: robots.hcl has no dict-valued field
    (``config/fleet.py`` ``_FIELD_TYPES``), so ``load_fleet`` would reject it
    as an unknown field at boot. Conversion time is where the operator can
    still fix it.
    """
    if isinstance(value, dict):
        raise SystemExit(
            f"robot '{rid}': {key} is a nested table, which robots.hcl does "
            f"not support. Remove it or move the values to top-level keys."
        )
    if isinstance(value, list):
        for item in value:
            _reject_tables(item, rid, key)


def _literal(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        return "[" + ", ".join(_literal(item) for item in value) + "]"
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def convert(toml_text: str) -> str:
    data = tomllib.loads(toml_text)
    robots = data.get("robot", [])
    if not robots:
        raise SystemExit("no [[robot]] entries found")

    chunks = []
    for index, robot in enumerate(robots):
        rid = robot.get("id")
        if not rid:
            raise SystemExit(f"robot #{index} has no 'id'")
        # 라벨도 HCL 문자열이므로 값과 같은 escaping을 거쳐야 한다.
        # 그러지 않으면 따옴표가 든 id가 `robot "A"B" {` 같은 깨진 HCL을 만든다.
        lines = [f"robot {_literal(str(rid))} {{"]
        width = max(
            (len(key) for key in robot if key != "id"),
            default=0,
        )
        for key, value in robot.items():
            if key == "id":
                continue
            _reject_tables(value, str(rid), key)
            lines.append(f"  {key.ljust(width)} = {_literal(value)}")
        lines.append("}")
        chunks.append("\n".join(lines))

    header = (
        "# Generated by scripts/convert-robots-toml-to-hcl.py\n"
        "# 주석은 변환되지 않는다. config/robots.hcl.example을 참고해 정리할 것.\n"
    )
    return header + "\n" + "\n\n".join(chunks) + "\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path, help="robots.toml 경로")
    parser.add_argument(
        "-o", "--output", type=Path, default=None, help="출력 경로 (기본: stdout)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="출력 파일이 이미 있어도 덮어쓴다 (기본: 거부)",
    )
    args = parser.parse_args(argv)

    out = convert(args.source.read_text(encoding="utf-8"))
    if args.output is None:
        sys.stdout.write(out)
    else:
        # 현장에서 한 번 돌리는 도구라 실수로 기존 robots.hcl을 날리면
        # 되돌릴 방법이 없다. 덮어쓰기는 명시적으로 요구하게 한다.
        if args.output.exists() and not args.force:
            raise SystemExit(
                f"{args.output} already exists; pass --force to overwrite"
            )
        args.output.write_text(out, encoding="utf-8")
        print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
